export const SOCIAL_LINK_STATE = {
  USED: "USED",
  FAILED: "FAILED",
  PENDING: "PENDING",
  EXPIRED: "EXPIRED",
  CANCELED: "CANCELED",
  SUCCEEDED: "SUCCEEDED",
};

export const SERVICE_CODE = {
  BILL: "BILL",
  ISEC: "ISEC",
  CASHBACK: "CASHBACK",
  ISEC_BULK: "ISEC_BULK",
  ISEC_REDEEM: "ISEC_REDEEM",
  ISEC_SCRATCH: "ISEC_SCRATCH",
  ISEC_SEND: "ISEC_SEND",
  ISEC_SAVE: "ISEC_SAVE",
  REFUND_MONEY: "REFUND_MONEY",
  CANCEL_ISEC: "CANCEL_ISEC",
  SOCIAL_REQUEST_MONEY_LINK: "SOCIAL_REQUEST_MONEY_LINK", // Tạo link yêu cầu thanh toán, Nhận tiền từ yêu cầu thanh toán
  SOCIAL_DONATE_MONEY: "SOCIAL_DONATE_MONEY", // thanh toán cho link yc Donate Money
  SOCIAL_SEND_MONEY: "SOCIAL_SEND_MONEY", // Thanh toán cho liên kết yêu cầu thanh toán
  SOCIAL_SEND_MONEY_LINK: "SOCIAL_SEND_MONEY_LINK", // Tạo link chuyển tiền
  SOCIAL_PAYME_RECEIVE_MONEY: "SOCIAL_PAYME_RECEIVE_MONEY", // Nhận tiền từ liên kết chuyển tiền
  SOCIAL_SEND_MONEY_LINK_RECIPIANT: "SOCIAL_SEND_MONEY_LINK_RECIPIANT", // Nhận tiền từ liên kết chuyển tiền khi chưa KYC
  ADD_MONEY: "ADD_MONEY", // Nạp tiền chuyển khoản, hoặc nhận lương nếu trong api lịch sử với tags có SALARY
  SALARY: "SALARY",
  MINUS_MONEY: "MINUS_MONEY",
  WITHDRAW_BANK_MANUAL: "WITHDRAW_BANK_MANUAL",
  DEPOSIT_BANK_MANUAL: "DEPOSIT_BANK_MANUAL",
  LINKED: "LINKED",
  DEPOSIT_PVCBANK: "DEPOSIT",
  SOCIAL_NAPAS_RECEIVE_MONEY: "SOCIAL_NAPAS_RECEIVE_MONEY",
  WITHDRAW_BANK_LINKED_PVCBANK: "WITHDRAW_BANK_LINKED_PVCBANK", // rút tiền từ payme vè pvcb
  WITHDRAW_BANK_GATEWAY: "WITHDRAW_BANK_GATEWAY", // rút tiền về tk ngân hàng hoặc atm, serviceWithdrawTo: BANK_ACCOUNT hoặc ATM_CARD
  WITHDRAW_BANK_LINKED_GATEWAY: "WITHDRAW_BANK_LINKED_GATEWAY", // rút tiên từ payme vè napas liên kết
  MOBILE_CARD: "MOBILE_CARD",
  MOBILE_TOPUP: "MOBILE_TOPUP",
  DEPOSIT: "DEPOSIT",
  SOCIAL_DONATE_MONEY_LINK: "SOCIAL_DONATE_MONEY_LINK", // tạo link và nhận tiền từ link đã tạo
  KYC_APPROVED: "KYC_APPROVED",
  KYC_REJECTED: "KYC_REJECTED",
  ISEC_RECEIVED: "ISEC_RECEIVED",
  ISEC_DONATED: "ISEC_DONATED",
  CASHBACK_BUYCARD: "CASHBACK_BUYCARD",
  CASHBACK_TOPUP: "CASHBACK_TOPUP",
  SOCIAL_REQUEST_MONEY_LINK_EXPIRED: "SOCIAL_REQUEST_MONEY_LINK_EXPIRED", // Link yêu cầu thanh toán hết hạn
  TRANSFER_PAYME: "TRANSFER_PAYME", // Chuyển, nhận tiền từ ví PayME,
  LOGIN_TRUST_DEVICE: "LOGIN_TRUST_DEVICE",
  GATEWAY_PAYMENT: "GATEWAY_PAYMENT", // chuyển tiền cho doanh nghiệp

  // SOCIAL_PAYMENT
  SOCIAL_PAYMENT_PAYME_RECEIVE_MONEY: "SOCIAL_PAYMENT_PAYME_RECEIVE_MONEY", // nhận tiền từ link v2
  SOCIAL_PAYMENT_SEND_MONEY: "SOCIAL_PAYMENT_SEND_MONEY", // Thanh toán link v2
  SOCIAL_PAYMENT_REQUEST_MONEY_LINK: "SOCIAL_PAYMENT_REQUEST_MONEY_LINK", // link yêu cầu v2
  SOCIAL_PAYMENT_SEND_MONEY_LINK: "SOCIAL_PAYMENT_SEND_MONEY_LINK", // link thanh toán v2

  SOCIAL_PAYMENT_DONATE_MONEY: "SOCIAL_PAYMENT_DONATE_MONEY", // thanh toán cho link donate v2
  SOCIAL_PAYMENT_DONATE_MONEY_LINK: "SOCIAL_PAYMENT_DONATE_MONEY_LINK", // Nhận tiền từ link donate

  SOCIAL_PAYMENT_NAPAS_RECEIVE_MONEY: "SOCIAL_PAYMENT_NAPAS_RECEIVE_MONEY", //Nhận tiền từ link qua NAPAS, chuyển tiền thành công (notify)
};

export const DETAILS_SERVICE_KEY = {
  ISEC: "ISEC", // Phát hành iSec
  ISEC_REDEEM: "ISEC_REDEEM", // Nhận tiền từ iSec
  ISEC_BULK: "ISEC_BULK", // Phát hành iSec sỉ

  BILL: "BILL", // Thanh toán hóa đơn

  MOBILE_TOPUP: "MOBILE_TOPUP", // Nạp tiền điện thoại
  MOBILE_CARD: "MOBILE_CARD", // Mua thẻ điện thoại

  /* Rút tiền - Theo phương thức */
  WITHDRAW_BANK_GATEWAY: "WITHDRAW_BANK_GATEWAY",
  WITHDRAW_BANK_LINKED_PVCBANK: "WITHDRAW_BANK_LINKED_PVCBANK",
  WITHDRAW_BANK_LINKED_GATEWAY: "WITHDRAW_BANK_LINKED_GATEWAY",

  DEPOSIT: "DEPOSIT", // Nạp tiền

  /* Hoàn tiền */
  CASHBACK: "CASHBACK",
  REFUND_MONEY: "REFUND_MONEY",

  SOCIAL_SEND_MONEY_LINK: "SOCIAL_SEND_MONEY_LINK", // Tạo link thanh toán

  SOCIAL_PAYME_RECEIVE_MONEY: "SOCIAL_PAYME_RECEIVE_MONEY", // ( Nhận thanh toán từ link về ví Payme)
  SOCIAL_NAPAS_RECEIVE_MONEY: "SOCIAL_NAPAS_RECEIVE_MONEY", // ( Nhận thanh toán từ link về thẻ napas)

  SOCIAL_REQUEST_MONEY_LINK: "SOCIAL_REQUEST_MONEY_LINK", // Tạo link yêu cầu thanh toán, Nhận tiền từ yêu cầu thanh toán

  SOCIAL_SEND_MONEY: "SOCIAL_SEND_MONEY", // Thanh toán link yêu cầu
  SOCIAL_DONATE_MONEY: "SOCIAL_DONATE_MONEY", // thanh toán cho link yc
  SOCIAL_DONATE_MONEY_LINK: "SOCIAL_DONATE_MONEY_LINK", // tạo link và nhận tiền từ link đã tạo
  TRANSFER_PAYME: "TRANSFER_PAYME", // Chuyển, nhận tiền từ ví PayME
  SOCIAL_SEND_MONEY_LINK_RECIPIANT: "SOCIAL_SEND_MONEY_LINK_RECIPIANT", // Nhận tiền từ liên kết chuyển tiền khi chưa KYC,
  ADD_MONEY: "ADD_MONEY", // Nap tien thu cong,
};

export const LINK_TYPE = {
  SEND_MONEY: "SEND_MONEY",
  REQUEST_MONEY: "REQUEST_MONEY",
};
