import * as types from "redux/types/school.types";
import * as actions from "redux/actions/school.actions";

export { types, actions };

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_REFRESH = "LOGIN_USER_REFRESH";

export const REGISTER_CLIENT = "REGISTER_CLIENT";
export const REGISTER_CLIENT_SUCCESS = "REGISTER_CLIENT_SUCCESS";
export const REGISTER_CLIENT_ERROR = "REGISTER_CLIENT_ERROR";

export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const GET_USER_INFORMATION_SUCCESS = "GET_USER_INFORMATION_SUCCESS";
export const GET_USER_INFORMATION_ERROR = "GET_USER_INFORMATION_ERROR";

export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const LOGOUT_USER = "LOGOUT_USER";

export const SEND_OTP_TRUST_DEVICE = "SEND_OTP_TRUST_DEVICE";
export const SEND_OTP_TRUST_DEVICE_SUCCESS = "SEND_OTP_TRUST_DEVICE_SUCCESS";
export const SEND_OTP_TRUST_DEVICE_ERROR = "SEND_OTP_TRUST_DEVICE_ERROR";

// history action type

export const GET_HISTORY_LIST = "GET_HISTORY_LIST";
export const GET_HISTORY_LIST_SUCCESS = "GET_HISTORY_LIST_SUCCESS";
export const GET_HISTORY_LIST_ERROR = "GET_HISTORY_LIST_ERROR";
export const GET_HISTORY_LIST_REFRESH = "GET_HISTORY_LIST_REFRESH";

export const GET_WALLET_BALANCE = "GET_WALLET_BALANCE";
export const GET_WALLET_BALANCE_SUCCESS = "GET_WALLET_BALANCE_SUCCESS";
export const GET_WALLET_BALANCE_ERROR = "GET_WALLET_BALANCE_ERROR";

export const GET_BANK_NAME = "GET_BANK_NAME";
export const GET_BANK_NAME_SUCCESS = "GET_BANK_NAME_SUCCESS";
export const GET_BANK_NAME_FAIL = "GET_BANK_NAME_FAIL";


//DETECT CARD NUMBER
export const GET_DETECT_CARD_NUMBER = "GET_DETECT_CARD_NUMBER";
export const GET_DETECT_CARD_NUMBER_SUCCESS = "GET_DETECT_CARD_NUMBER_SUCCESS";
export const GET_DETECT_CARD_NUMBER_FAIL = "GET_DETECT_CARD_NUMBER_FAIL";

//get list bank
export const GET_LIST_BANKS = "GET_LIST_BANKS";
export const GET_LIST_BANKS_SUCCESS = "GET_LIST_BANKS_SUCCESS";
export const GET_LIST_BANKS_FAIL = "GET_LIST_BANK_FAIL";

//nạp tiền 
export const DEPOSIT_PAYME = "DEPOSIT_PAYME";
export const DEPOSIT_PAYME_SUCCESS = "DEPOSIT_PAYME_SUCCESS";
export const DEPOSIT_PAYME_FAIL = "DEPOSIT_PAYME_FAIL";

//get fee service
export const GET_FEE_SERVICE = "GET_FEE_SERVICE";
export const GET_FEE_SERVICE_SUCCESS = "GET_FEE_SERVICE_SUCCESS";
export const GET_FEE_SERVICE_FAIL = "GET_FEE_SERVICE_FAIL";