import * as types from "./school.types";
import * as actions from "redux/actions/school.actions";

export { types, actions };

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_REFRESH = "LOGIN_USER_REFRESH";

export const REGISTER_CLIENT = "REGISTER_CLIENT";
export const REGISTER_CLIENT_SUCCESS = "REGISTER_CLIENT_SUCCESS";
export const REGISTER_CLIENT_ERROR = "REGISTER_CLIENT_ERROR";

export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const GET_USER_INFORMATION_SUCCESS = "GET_USER_INFORMATION_SUCCESS";
export const GET_USER_INFORMATION_ERROR = "GET_USER_INFORMATION_ERROR";

export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const LOGOUT_USER = "LOGOUT_USER";

export const SEND_OTP_TRUST_DEVICE = "SEND_OTP_TRUST_DEVICE";
export const SEND_OTP_TRUST_DEVICE_SUCCESS = "SEND_OTP_TRUST_DEVICE_SUCCESS";
export const SEND_OTP_TRUST_DEVICE_ERROR = "SEND_OTP_TRUST_DEVICE_ERROR";

// history action type

export const GET_HISTORY_LIST = "GET_HISTORY_LIST";
export const GET_HISTORY_LIST_SUCCESS = "GET_HISTORY_LIST_SUCCESS";
export const GET_HISTORY_LIST_ERROR = "GET_HISTORY_LIST_ERROR";
export const GET_HISTORY_LIST_REFRESH = "GET_HISTORY_LIST_REFRESH";

export const GET_WALLET_BALANCE = "GET_WALLET_BALANCE";
export const GET_WALLET_BALANCE_SUCCESS = "GET_WALLET_BALANCE_SUCCESS";
export const GET_WALLET_BALANCE_ERROR = "GET_WALLET_BALANCE_ERROR";

export const GET_BANK_NAME = "GET_BANK_NAME";
export const GET_BANK_NAME_SUCCESS = "GET_BANK_NAME_SUCCESS";
export const GET_BANK_NAME_FAIL = "GET_BANK_NAME_FAIL";

// REGISTER 
export const REGISTER_SEND_OTP = "REGISTER_SEND_OTP";
export const REGISTER_SEND_OTP_SUCCESS = "REGISTER_SEND_OTP_SUCCESS";
export const REGISTER_SEND_OTP_ERROR = "REGISTER_SEND_OTP_ERROR";

export const REGISTER_SEND_FORM = "REGISTER_SEND_FORM";
export const REGISTER_SEND_FORM_SUCCESS = "REGISTER_SEND_FORM_SUCCESS";
export const REGISTER_SEND_FORM_ERROR = "REGISTER_SEND_FORM_ERROR";

export const REGISTER_SEND_CHECK_OTP = "REGISTER_SEND_CHECK_OTP";
export const REGISTER_SEND_CHECK_OTP_SUCCESS = "REGISTER_SEND_CHECK_OTP_SUCCESS";
export const REGISTER_SEND_CHECK_OTP_ERROR = "REGISTER_SEND_CHECK_OTP_ERROR";
